version: "2"
services: 
    mobile-food-permits-api:
        build:
            dockerfile: ./src/MobileFoodPermits.Service/Dockerfile
            context: .
        ports:
            - "5000:80"
        volumes: 
            - ./data/:/data

